shell = 'zsh'

[templates]
completions_fpath = 'fpath=( "{{ dir }}/completions" $fpath )'

[plugins.asdf]
github = 'asdf-vm/asdf'
tag = 'v0.14.1'
use = ['asdf.sh']
apply = ['source', 'completions_fpath']

[plugins.dracula]
github = 'dracula/zsh'

[plugins.fzf]
local = "~/.fzf"
dir = "bin"
apply = ["PATH"]

[plugins.fzf-zsh]
local = "~/.fzf"
dir = "shell"
use = [
    "completion.zsh",
    "key-bindings.zsh",
]
