[templates]
completions_fpath = 'fpath=( "{{ dir }}/completions" $fpath )'

[plugins.fzf]
github = 'junegunn/fzf'
use = ['shell/*.zsh']

[plugins.dracula]
github = 'dracula/zsh'

[plugins.asdf]
github = 'asdf-vm/asdf'
tag = 'v0.8.0'
use = ['asdf.sh']
apply = ['source', 'completions_fpath']